# Generated by Django 3.0.3 on 2020-07-26 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_auto_20200725_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
