# Generated by Django 3.0.3 on 2020-07-26 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_auto_20200726_1223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='time_modified',
            new_name='datetime_modified',
        ),
    ]
