# Generated by Django 3.0.3 on 2020-07-27 15:57

from django.db import migrations, models
import network.models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0014_remove_user_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='color',
            field=models.CharField(choices=[('pink', 'Pink'), ('yellow', 'Yellow'), ('green', 'Green'), ('lightblue', 'Blue'), ('purple', 'Purple')], default=network.models.random_color, max_length=20),
        ),
    ]
